### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by acusset** [ESGI-IW3-2016-01/projet-symfony#10]
Code should be written in english only. This includes class names, fields, properties, methods etc.

We'll use[ Easy Admin Translation](http://symfony.com/doc/current/bundles/EasyAdminBundle/tutorials/i18n.html) to translate admin panel to French.

**Comment by MorinAlexandre** [comment]
Certains menus non traduits

**Comment by acusset** [comment]
Lequels ?
