### ISSUE TITLE
Ajout greetingText

### ISSUE THREAD

**Issue by MorinAlexandre** [ESGI-IW3-2016-01/projet-symfony#16]
A new entity was found through the relationship 'AppBundle\Entity\Facebook\GreetingText#locale' that was not configured to cascade persist operations for entity: default. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ManyToOne(..,cascade={"persist"}).

**Comment by MorinAlexandre** [comment]
Quand on essaye de mettre deux messages avec le meme langage : 
An exception occurred while executing 'INSERT INTO greeting_text (id, text, enabled, locales_id) VALUES (?, ?, ?, ?)' with params [4, "test", 1, 14]:

SQLSTATE[23505]: Unique violation: 7 ERROR: duplicate key value violates unique constraint "uniq_aed77173164006b8"
DETAIL: Key (locales_id)=(14) already exists.

**Comment by acusset** [comment]
Oui il n'y a qu'une seule phrase par locale. Il y a bien un OneToOne mais il retire pas de la liste...

**Comment by acusset** [comment]
C'est fait -> https://github.com/ESGI-IW3-2016-01/projet-symfony/commit/2745743b2749f174b4cdb68982753bc2fc28d824
