### ISSUE TITLE
Ajout d'une classe

### ISSUE THREAD

**Issue by MorinAlexandre** [ESGI-IW3-2016-01/projet-symfony#17]
An exception occurred while executing 'INSERT INTO student_group (id, name, scholar_year, group_number, promotion_id, school_id, calendar_id) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [3, "5 IW 3", "5", null, 1, 1, 1]:

SQLSTATE[23502]: Not null violation: 7 ERROR: null value in column "group_number" violates not-null constraint
DETAIL: Failing row contains (3, 1, 1, 5 IW 3, 5, null, 1).

**Comment by acusset** [comment]
C'est fix !
