### ISSUE TITLE
Upload de l'agenda

### ISSUE THREAD

**Issue by MorinAlexandre** [ESGI-IW3-2016-01/projet-symfony#5]
En fonction de la classe

**Comment by acusset** [comment]
Check if we can upload files to Heroku /!\ (we might need AWS file storage extension)

Steps :
1. Upload  form ([see official doc](https://symfony.com/doc/current/controller/upload_file.html))
2. Check file extension (.ical / .ics) and size
3. Check if the directories exists (see above), if not, create directory structure obviously ([see official doc](https://symfony.com/doc/current/components/filesystem.html))
4. Place the uploaded files in `/var/data/upload/calendars` where they wait to be processed
5. (Optional) Get calendar via http url

Once they are processed (feature #4 ), I'll move the files to another directory

Add parameters for directories location in the `config.yml` file :

    parameters:
        locale: en
        ical_upload_directory: '%kernel.root_dir%/../var/data/upload/calendars'
        ical_success_directory: '%kernel.root_dir%/../var/data/upload/calendars/success'
        ical_error_directory: '%kernel.root_dir%/../var/data/upload/calendars/error'
